import Head from 'next/head'
import Image from 'next/image'
import {
  SiAdobexd, SiFigma, SiPython, SiJavascript, SiReact, SiHtml5, SiCss3,
  SiTailwindcss, SiAzuredevops, SiDocker, SiKubernetes, SiGithub, SiPostgresql,
  SiMysql, SiSolidity, SiEthereum
} from "react-icons/si"
import { DiDjango, DiSass } from "react-icons/di"
import { TbBrandReactNative } from "react-icons/tb"
import { motion } from 'framer-motion'
import ReactTyped from 'react-typed'
import Slider from "react-slick";
import NavBar from '../components/home/nav'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { fadeIn, slideInLeftFast, slideInRightFast, slideInFromBottom, stagger, antiStagger } from '../components/animations'

const imageLoader = require("../loader");

export default function Home() {
  const settings = {
    dots: true,
    infinite: true,
    speed: 5000,
    slidesToShow: 5,
    slidesToScroll: 4,
    autoplay: true,
    autoplaySpeed: 5000,
  };
  return (
    <motion.div exit={{ opacity: 0 }} initial="initial" animate="animate">
      <Head>
        <title>Hashim Athman | Full Stack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Montserrat:wght@300;400;500&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </Head>

      <motion.div variants={stagger} className='h-screen px-12 py-1'>
        <NavBar />
        <motion.div variants={fadeIn} className='w-full text-center my-10 mt-5 tracking-widest'>

          <motion.h1 className="text-[1.5rem] mb-1 tracking-[0.2rem]">Hashim Athman</motion.h1>
          <motion.h1 className="text-[1.2rem] mb-1">Software Developer/Admin</motion.h1>
          <motion.div>
            <h2>My work is always a <span className="text-[#f60961]">Wooow</span></h2>

          </motion.div>
        </motion.div>

        <motion.div variants={antiStagger} className='flex flex-wrap justify-between items-start'>
          <motion.div variants={slideInLeftFast} className='w-full flex flex-col justify-start items-start pr-20 lg:order-first lg:flex-1'>
            <div>
              <h6>BIOGRAPHY</h6>
              <p>Work for money and design for love! I'm Hashim, a full stack developer based in Kenya</p>
            </div>

            <div>
              <h6>CONTACT</h6>
              <p>Mombasa, Kenya</p>
              <p>contact@hashimathman.com</p>
              <p>+254 70146 7872</p>

            </div>

            <div>
              <h6>SERVICES</h6>
              <p>UI/UX Design</p>
              <p>Backend Development</p>
              <p>Frontend Development</p>
              <p>Mobile Development</p>
            </div>
          </motion.div>

          <motion.div variants={fadeIn} className='w-full relative -top-2 order-first px-3'>
            <div className='h-64 relative p-10 border-solid border-2 rounded-full'>
              <div className='h-full p-5 border-solid border-2 rounded-full bg-[#B7C6C9] relative'>
                {/* <Image className='absolute bottom-0' src="/../public/assets/pict.png" width="900" height="700" alt="picture" /> */}
              </div>

            </div>
          </motion.div>

          <motion.div variants={slideInRightFast} className='w-full flex flex-col justify-end items-end text-right lg:flex-1'>
            <div>
              <h6>PROFESSIONAL<br />CERTIFICATIONS</h6>
              <p>Google UI/UX certification</p>
              <p>Google Project Management certification</p>
              <p>Google IT Support certification</p>
            </div>

            <div>
              <h6><br />OTHER CERTIFICATIONS</h6>
              <p className='mb-2'>Advanced CSS and Sass: Flexbox, Grid, Animations</p>
              <p>Ethereum and Solidity: The Complete Developer’s
                Guide</p>
            </div>

            <div>
              <h6>PROJECTS DONE</h6>
              <h2>10</h2>
            </div>
          </motion.div>



        </motion.div>
        <motion.div variants={slideInFromBottom}>
          <div className='text-center mt-8'>
            <h2>Skills</h2>
          </div>
          <Slider {...settings} className="mx-48 my-3">
            <div>
              <SiAdobexd size={35} color="#450135" />
              <p className='text-[#45013] mt-1 '>Adobe Xd</p>
            </div>
            <div>
              <SiFigma size={35} color="#9d56f7" />
              <p className='text-[#45013] mt-1 '>Figma</p>
            </div>
            <div>
              <SiPython size={35} color="#326a96" />
              <p className='mt-1 '>Python</p>
            </div>
            <div>
              <DiDjango size={35} color="#092d1f" />
            </div>
            <div>
              <SiJavascript size={35} color="#efd81d" />
              <p className='mt-1 '>Javascript</p>
            </div>
            <div>
              <SiReact size={35} color="#5ed3f3" />
              <p className='mt-1 '>React</p>
            </div>
            <div>
              <TbBrandReactNative size={35} color="#5ed3f3" />
              <p className='mt-1 '>React Native</p>
            </div>
            <div>
              <SiHtml5 size={35} color="#dd4b25" />
              <p className='mt-1 '>Html</p>
            </div>
            <div>
              <SiCss3 size={35} color="#254bdd" />
              <p className='mt-1 '>CSS</p>
            </div>
            <div>
              <SiTailwindcss size={35} color="#36b7f0" />
              <p className='mt-1 '>Tailwind CSS</p>
            </div>

            <div>
              <DiSass size={35} color="#c76494" />

            </div>

            <div>
              <SiAzuredevops size={35} color="#1391f7" />
              <p className='mt-1 '>Devops</p>
            </div>
            <div>
              <SiDocker size={35} color="#00a5d3" />
              <p className='mt-1 '>Docker</p>
            </div>
            <div>
              <SiKubernetes size={35} color="#306adf" />
              <p className='mt-1 '>Kubernetes</p>
            </div>
            <div>
              <SiGithub size={35} color="#1a1e22" />
              <p className='mt-1 '>Github</p>
            </div>
            <div>
              <SiPostgresql size={35} color="#31648c" />
              <p className='mt-1 '>Postgresql</p>
            </div>
            <div>
              <SiMysql size={35} color="#005e88" />
              <p className='mt-1 '>Mysql</p>
            </div>

            <div>
              <SiSolidity size={35} color="#363636" />
              <p className='mt-1 '>Solidity</p>
            </div>
            <div>
              <SiEthereum size={35} color="#5b6087" />
              <p className='mt-1 '>Ethereum</p>
            </div>

          </Slider>
        </motion.div>
      </motion.div>
    </motion.div>
  )
}
