import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/home/nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hashim Athman | Full Stack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full px-24 py-3'>
        <NavBar />
      </div>
    </div>
  )
}
